[2023-07-11T15:03:08.833+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T15:02:22.500420+00:00 [queued]>
[2023-07-11T15:03:08.853+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T15:02:22.500420+00:00 [queued]>
[2023-07-11T15:03:08.854+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T15:03:08.854+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-07-11T15:03:08.854+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T15:03:08.876+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2023-07-11 15:02:22.500420+00:00
[2023-07-11T15:03:08.894+0000] {standard_task_runner.py:55} INFO - Started process 50391 to run task
[2023-07-11T15:03:08.903+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'load_task', 'manual__2023-07-11T15:02:22.500420+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmp7l873fmy']
[2023-07-11T15:03:08.908+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask load_task
[2023-07-11T15:03:09.107+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.load_task manual__2023-07-11T15:02:22.500420+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T15:03:09.252+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-11T15:02:22.500420+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-11T15:02:22.500420+00:00
[2023-07-11T15:03:09.285+0000] {logging_mixin.py:137} INFO - Connection to the database successful!
[2023-07-11T15:03:09.291+0000] {logging_mixin.py:137} INFO - Table created successfully!
[2023-07-11T15:03:09.326+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 139, in load_to_rds
    cursor.executemany(insert_query, data)
psycopg2.errors.NotNullViolation: null value in column "id" of relation "listings" violates not-null constraint
DETAIL:  Failing row contains (null, 3501/151 George Street, Brisbane QLD 4000, 1500, 3, 2, 2, Unit, 4000).

[2023-07-11T15:03:09.349+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=load_task, execution_date=20230711T150222, start_date=20230711T150308, end_date=20230711T150309
[2023-07-11T15:03:09.363+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 115 for task load_task (null value in column "id" of relation "listings" violates not-null constraint
DETAIL:  Failing row contains (null, 3501/151 George Street, Brisbane QLD 4000, 1500, 3, 2, 2, Unit, 4000).
; 50391)
[2023-07-11T15:03:09.397+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T15:03:09.434+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
