[2023-07-11T14:47:31.018+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-11T14:41:45.465451+00:00 [queued]>
[2023-07-11T14:47:31.035+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-11T14:41:45.465451+00:00 [queued]>
[2023-07-11T14:47:31.036+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T14:47:31.036+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 4
[2023-07-11T14:47:31.036+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-11T14:47:31.048+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_task> on 2023-07-11 14:41:45.465451+00:00
[2023-07-11T14:47:31.056+0000] {standard_task_runner.py:55} INFO - Started process 42392 to run task
[2023-07-11T14:47:31.061+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_etl_dag', 'transform_task', 'manual__2023-07-11T14:41:45.465451+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_etl_dag.py', '--cfg-path', '/tmp/tmpei6z4417']
[2023-07-11T14:47:31.065+0000] {standard_task_runner.py:83} INFO - Job 89: Subtask transform_task
[2023-07-11T14:47:31.211+0000] {task_command.py:389} INFO - Running <TaskInstance: real_estate_etl_dag.transform_task manual__2023-07-11T14:41:45.465451+00:00 [running]> on host ip-172-31-34-219.ap-southeast-2.compute.internal
[2023-07-11T14:47:31.357+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=real_estate_etl_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-11T14:41:45.465451+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-11T14:41:45.465451+00:00
[2023-07-11T14:47:31.394+0000] {logging_mixin.py:137} INFO - DATAFRAME DIMENSIONS: (0, 0)
[2023-07-11T14:47:31.394+0000] {logging_mixin.py:137} INFO - None
[2023-07-11T14:47:31.395+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/real_estate_etl_dag.py", line 76, in clean_data
    df = df[df['price_per_week'].str.contains('\$') & df['price_per_week'].str.contains('\d')]
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'price_per_week'
[2023-07-11T14:47:31.422+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_etl_dag, task_id=transform_task, execution_date=20230711T144145, start_date=20230711T144731, end_date=20230711T144731
[2023-07-11T14:47:31.438+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 89 for task transform_task ('price_per_week'; 42392)
[2023-07-11T14:47:31.478+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-11T14:47:31.537+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
